# Generated by Django 4.0.3 on 2022-06-07 10:33

from urllib import request
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def create_groups(apps, schema_migration):
    # ensure that permissions have been created
    emit_post_migrate_signal(verbosity=1, interactive=False, db='default')

    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_user = Permission.objects.get(codename='add_user')
    change_user = Permission.objects.get(codename='change_user')
    delete_user = Permission.objects.get(codename='delete_user')
    view_user = Permission.objects.get(codename='view_user')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    delete_client = Permission.objects.get(codename='delete_client')
    view_client = Permission.objects.get(codename='view_client')

    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    delete_contract = Permission.objects.get(codename='delete_contract')
    view_contract = Permission.objects.get(codename='view_contract')

    add_event = Permission.objects.get(codename='add_event')
    change_event = Permission.objects.get(codename='change_event')
    delete_event = Permission.objects.get(codename='delete_event')
    view_event = Permission.objects.get(codename='view_event')


    management_permissions = [
        add_client,
        change_client,
        delete_client,
        view_client,
        add_contract,
        change_contract,
        delete_contract,
        view_contract,
        add_event,
        view_event,
        change_event,
        delete_event,
        add_user,
        view_user,
        change_user,
        delete_user,
    ]

    support_permissions = [
        add_event,
        change_event,
        delete_event,
        view_event,
        # view_contract,
        # view_client,
    ]


    sale_permissions = [
        add_client,
        change_client,
        delete_client,
        view_client,
        add_contract,
        change_contract,
        delete_contract,
        view_contract,
        add_event,
        view_event,
    ]

    management = Group(name='Management')
    management.save()
    management.permissions.set(management_permissions)

    support = Group(name='Support')
    support.save()
    support.permissions.set(support_permissions)

    sale = Group(name='Sale')
    sale.save()
    sale.permissions.set(sale_permissions)
    
    # for user in User.objects.all():
    #     user.is_staff = True
    #     user.save()
    #     if user.role == 'Management':
    #         user.is_superuser = True
    #         user.save()
    #         management.user_set.add(user)
    #     if user.role == 'Support':
    #         support.user_set.add(user)
    #     if user.role == 'Sale':
    #         sale.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
